Circuits & programs renamed from 'swap' to 'swaps'.
Anchor doesn't like 'swap' as a name for a program, and crashing with the error:
```
thread 'main' panicked at 'Empty structs are allowed.', lang/syn/src/idl/file.rs:765:14
```