Swap example (#10)
* Add swap example

* Update README

* Add @lightprotocol/cli dep to the projects

* Add @lightprotocol/cli package dependency to swap example

* Update swap example corresponding to the new light-cli

* Circuits & programs renamed from 'swap' to 'swaps'.

Anchor doesn't like 'swap' as a name for a program, and crashing with the error:
```
thread 'main' panicked at 'Empty structs are allowed.', lang/syn/src/idl/file.rs:765:14
```

* prettier formatting